name: Pixel 7 Mali Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android NDK
        uses: android-actions/setup-android@v3

      - name: Make Gradle Executable
        run: |
          find . -name "gradlew" -exec chmod +x {} \;

      - name: Build Optimized APK
        run: |
          # This command attempts to build even if the project is in a subfolder
          if [ -f "./gradlew" ]; then
            ./gradlew assembleDebug --stacktrace
          else
            cd $(find . -name "gradlew" -printf '%h' -quit) && ./gradlew assembleDebug --stacktrace
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: aPS3e-Pixel7-Optimized
          path: "**/*.apk"
